name: ⚡ Update Recent Activity

on:
  # Run every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  update-readme:
    name: Update Activity in README
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⚡ Update README with Recent GitHub Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "chore: ⚡ auto-update recent activity [skip ci]"
          MAX_LINES: 10
          # Adds emojis to each activity type automatically
          URL_TEXT: "{REPO}"
          COMMENTS_ACTIVITY: true
          ISSUE_OPENED: "🐛 Opened issue #{ID} in {REPO}"
          ISSUE_CLOSED: "✅ Closed issue #{ID} in {REPO}"
          PR_OPENED: "🔀 Opened PR #{ID} in {REPO}"
          PR_MERGED: "🎉 Merged PR #{ID} in {REPO}"
          PR_REVIEWED: "👀 Reviewed PR #{ID} in {REPO}"
          PUSH: "⚡ Pushed {NUM_COMMITS} commit(s) to {REPO}"
          FORK: "🍴 Forked {REPO}"
          STAR: "⭐ Starred {REPO}"
          RELEASE: "🚀 Released {ID} in {REPO}"
          WIKI_EDIT: "📝 Edited wiki in {REPO}"
          COMMENT_CREATED: "💬 Commented on {ID} in {REPO}"
